/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "paper.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

char *
pap_proc_1(argp, clnt)
	pap_in *argp;
	CLIENT *clnt;
{
	static pap_out clnt_res;

	memset((char *)clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, PAP_PROC, xdr_pap_in, argp, xdr_pap_out, clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (clnt_res);
}
