/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PAPER_H_RPCGEN
#define _PAPER_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct pap_in {
	int arg0;
	char arg1[20];
	char arg2[20];
	char arg3[20];
};
typedef struct pap_in pap_in;
#ifdef __cplusplus
extern "C" bool_t xdr_pap_in(XDR *, pap_in*);
#elif __STDC__
extern  bool_t xdr_pap_in(XDR *, pap_in*);
#else /* Old Style C */
bool_t xdr_pap_in();
#endif /* Old Style C */


typedef char pap_out[2000];
#ifdef __cplusplus
extern "C" bool_t xdr_pap_out(XDR *, pap_out);
#elif __STDC__
extern  bool_t xdr_pap_out(XDR *, pap_out);
#else /* Old Style C */
bool_t xdr_pap_out();
#endif /* Old Style C */


#define PAP_PROG ((rpc_uint)0x3543000)
#define PAP_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define PAP_PROC ((rpc_uint)1)
extern "C" char * pap_proc_1(pap_in *, CLIENT *);
extern "C" char * pap_proc_1_svc(pap_in *, struct svc_req *);

#elif __STDC__
#define PAP_PROC ((rpc_uint)1)
extern  char * pap_proc_1(pap_in *, CLIENT *);
extern  char * pap_proc_1_svc(pap_in *, struct svc_req *);

#else /* Old Style C */
#define PAP_PROC ((rpc_uint)1)
extern  char * pap_proc_1();
extern  char * pap_proc_1_svc();
#endif /* Old Style C */

#endif /* !_PAPER_H_RPCGEN */
