/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "paper.h"

bool_t
xdr_pap_in(xdrs, objp)
	XDR *xdrs;
	pap_in *objp;
{

	if (!xdr_int(xdrs, &objp->arg0))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->arg1, 20, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->arg2, 20, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->arg3, 20, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_pap_out(xdrs, objp)
	XDR *xdrs;
	pap_out objp;
{

	if (!xdr_vector(xdrs, (char *)objp, 2000, sizeof(char), (xdrproc_t)xdr_char))
		return (FALSE);
	return (TRUE);
}
