/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CAL_H_RPCGEN
#define _CAL_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct cal_in {
	long arg1;
	long arg2;
	long arg3;
};
typedef struct cal_in cal_in;
#ifdef __cplusplus
extern "C" bool_t xdr_cal_in(XDR *, cal_in*);
#elif __STDC__
extern  bool_t xdr_cal_in(XDR *, cal_in*);
#else /* Old Style C */
bool_t xdr_cal_in();
#endif /* Old Style C */


typedef long cal_out;
#ifdef __cplusplus
extern "C" bool_t xdr_cal_out(XDR *, cal_out*);
#elif __STDC__
extern  bool_t xdr_cal_out(XDR *, cal_out*);
#else /* Old Style C */
bool_t xdr_cal_out();
#endif /* Old Style C */


#define CAL_PROG ((rpc_uint)0x3543000)
#define CAL_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define CAL_PROC ((rpc_uint)1)
extern "C" cal_out * cal_proc_1(cal_in *, CLIENT *);
extern "C" cal_out * cal_proc_1_svc(cal_in *, struct svc_req *);

#elif __STDC__
#define CAL_PROC ((rpc_uint)1)
extern  cal_out * cal_proc_1(cal_in *, CLIENT *);
extern  cal_out * cal_proc_1_svc(cal_in *, struct svc_req *);

#else /* Old Style C */
#define CAL_PROC ((rpc_uint)1)
extern  cal_out * cal_proc_1();
extern  cal_out * cal_proc_1_svc();
#endif /* Old Style C */

#endif /* !_CAL_H_RPCGEN */
