/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "add.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

add_out *
add_proc_1(argp, clnt)
	add_in *argp;
	CLIENT *clnt;
{
	static add_out clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, ADD_PROC, xdr_add_in, argp, xdr_add_out, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
